# -*- coding: utf-8 -*-
"""Prova_1_CM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rBiV77qkgMdrnrIKJtSNr7wMCB4eSO0i
"""

import numpy as np
from numpy import pi, sin, cos, sqrt
from sympy import *
from rich.console import Console

s=True
while(s==True):
    a = input('Deseja rodar o programa s ou n?: ')
    if(a == 's'):
        console = Console()
        r, t = symbols('r,t')
        r2 = 0.17
        r3 = 0.58
        w2 = 130.27
        theta2 = w2*t

        console.print('\n\n\nFunção Espaço Para r1\n', style='bold red')
        r1 = r2*cos(theta2) + sqrt((r3**2)-((r2**2))*(sin(theta2)**2))
        print(r1)
        print('\n\n')

        console.print('\n\nFunção Velocidade\n', style='bold green')
        v = diff(r1,t)
        print(v)
        print('\n\n')

        console.print('\n\nFunção Aceleração\n', style='bold yellow')
        a = diff(v,t)
        print(a)
        print('\n\n')

        y = (t, 0, 2)
        console.print('\n\n\nGráfico Para a Função Espaço Para r1\n', style='bold red')
        plot(r1, y)
        console.print('\n\nGráfico Para a Função Velocidade\n', style='bold green')

        plot(v, y)
        console.print('\n\nGráfico Para a Função Aceleração\n', style='bold yellow')

        plot(a,y)
        s = True
    else:
        s = False